# tomcat
server:
  port: 8002
spring:
  application:
    name: chaofen-backup
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}	# 注册到consul的服务名称
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
# backup datasource
mango:
  backup:
    datasource:
      host: gz-cdb-76yl59np.sql.tencentcdb.com:58019
      userName: root
      password: Le@19940114
      database: mango